### ISSUE TITLE
add oidc middleware

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-pkg#8]
can be based on the reva implementation: https://github.com/cs3org/reva/blob/master/pkg/auth/manager/oidc/oidc.go#L94

**Comment by tboerger** [comment]
It would be great to implement that for the micro plugins beside the basic, digest and ldap auth. Than not only us can use it ;)

**Comment by butonic** [comment]
true. I'd like to give it an iteration in ocis-pkg, because the mentioned code already contains specific hacks for kopano konnectd :man_shrugging: 

ultimately this should go upstream!

**Comment by DeepDiver1975** [comment]
fixed with #12
